# -*- coding: utf-8 -*-
"""tic_tac_toe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DUyTzmO2pOOFUjr4UM_KwBMrJQ95tMYX
"""

board = [] #this list contains 3 lists, each of 3 elements, each element being a single character

def print_board():
  pass
  
def check_mark():
  pass

def place_mark():
  pass

def check_win():
  pass

def main():
  pass

main()